# brew bundle --verbose

brew "mise"
brew "yarn"

brew "mysql"

brew "imagemagick"
brew "ffmpeg"

brew "starship"

brew "eza"
brew "bat"
brew "fzf"
brew "fd"
brew "jq"
brew "htop"
brew "ripgrep"
brew "dua-cli"
brew "httpie"
brew "awscli"
brew "difftastic"
