# gruvbox
# ayu_dark
# argonaut
# tokyo_night
# tomorrow_night_bright

import = [
  "~/.config/alacritty/themes/themes/argonaut.toml"
]

[env]
TERM = "xterm-256color"

[colors.primary]
background = '#000000'
# background = '#0d0d0d'

[colors.cursor]
text = 'CellForeground'
cursor = '#424242'

[window]
# opacity = 0.8
# blur = true
decorations = "Buttonless"
# startup_mode = "Maximized"

dynamic_padding = true
# padding.x = 10
# padding.y = 10

option_as_alt = "Both"

[cursor]
style.blinking = "On"

[font]
normal.family = "MesloLGS NF"
size = 18

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" }, # Skip word left
  { key = "Left",  mods = "Alt", chars = "\u001BB" }  # Skip word right
]
