# https://starship.rs/config/

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$localip\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$ruby\
$aws\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$container\
$status\
$character"""

# format = """
# $username\
# $hostname\
# $localip\
# $directory\
# $character"""

# right_format = """
# $git_branch\
# $git_commit\
# $git_state\
# $git_metrics\
# $git_status\
# $ruby"""

# add_newline = false

[username]
format = '[$user]($style)'

[hostname]
ssh_symbol = '@'
format = '[$ssh_symbol$hostname]($style) '

[directory]
# style = 'cyan'
read_only = " \uf023"
# repo_root_style = 'bold cyan'
# truncate_to_repo = false
# before_repo_root_style = "bold black"
# fish_style_pwd_dir_length = 1
truncation_symbol = '…/'

[git_branch]
symbol = "\uf126 "
format = '[$symbol$branch(:$remote_branch)]($style) '

# [git_metrics]
# disabled = false

[git_status]
# format = '([$ahead_behind]($style) )'
ahead = "\u2191"  # \u2191$count
behind = "\u2193" # \u21e3$count
# style = "bold blue"

[jobs]
symbol = "\uf013 "

[ruby]
symbol = "\ueb48 " # "\ue21e "
version_format = '${raw}'
format = '[$symbol($version )]($style)'
detect_extensions = []

[aws]
symbol = "\uf270 "
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
expiration_symbol = "\u00D7"

[cmd_duration]
format = "[\uf4e3 $duration]($style) " # \uf252
min_time = 5000

[[battery.display]]
threshold = 10
style = 'bold red'

[[battery.display]]
threshold = 30
style = 'bold yellow'

[time]
disabled = false
format = "[\uf017 $time]($style) "
time_range = '20:00:00-8:00:00'

[status]
disabled = false
format = '[\[$common_meaning$signal_name$maybe_int\]]($style) '
