[metadata]
name = "Tailwind Slate Dark"
author = "Lucas Repolês (lucas@repoles.com)"
origin_url = "https://tailwindcss.com/docs/colors"

[colors]
# Basic colors
foreground = "#f8fafc"      # slate-50
background = "#0f172a"      # slate-900
cursor_bg = "#f8fafc"       # slate-50
cursor_fg = "#0f172a"       # slate-900
cursor_border = "#f8fafc"   # slate-50

# Selection colors
selection_fg = "#0f172a"    # slate-900
selection_bg = "#64748b"    # slate-500

# Scrollbar
scrollbar_thumb = "#475569" # slate-600

# Split borders
split = "#334155"           # slate-700

# ANSI colors (0-7: normal)
ansi = [
    "#1e293b",  # black (slate-800)
    "#ef4444",  # red (red-500)
    "#22c55e",  # green (green-500)
    "#eab308",  # yellow (yellow-500)
    "#3b82f6",  # blue (blue-500)
    "#a855f7",  # magenta (purple-500)
    "#06b6d4",  # cyan (cyan-500)
    "#e2e8f0",  # white (slate-200)
]

# Bright ANSI colors (8-15: bright)
brights = [
    "#475569",  # bright black (slate-600)
    "#f87171",  # bright red (red-400)
    "#4ade80",  # bright green (green-400)
    "#facc15",  # bright yellow (yellow-400)
    "#60a5fa",  # bright blue (blue-400)
    "#c084fc",  # bright magenta (purple-400)
    "#22d3ee",  # bright cyan (cyan-400)
    "#f1f5f9",  # bright white (slate-100)
]

# Tab bar colors
[colors.tab_bar]
background = "#020617"      # slate-950

[colors.tab_bar.active_tab]
bg_color = "#334155"        # slate-700
fg_color = "#f8fafc"        # slate-50

[colors.tab_bar.inactive_tab]
bg_color = "#0f172a"        # slate-900
fg_color = "#94a3b8"        # slate-400

[colors.tab_bar.inactive_tab_hover]
bg_color = "#1e293b"        # slate-800
fg_color = "#e2e8f0"        # slate-200

[colors.tab_bar.new_tab]
bg_color = "#0f172a"        # slate-900
fg_color = "#64748b"        # slate-500

[colors.tab_bar.new_tab_hover]
bg_color = "#1e293b"        # slate-800
fg_color = "#f8fafc"        # slate-50
