complete -c rails -f -n __fish_use_subcommand -a server    -d 'Start the Rails server'
complete -c rails -f -n __fish_use_subcommand -a console   -d 'Start the Rails console'
complete -c rails -f -n __fish_use_subcommand -a generate  -d 'Generate new code'
complete -c rails -f -n __fish_use_subcommand -a destroy   -d 'Undo generated code'
complete -c rails -f -n __fish_use_subcommand -a dbconsole -d 'Start a database console'
complete -c rails -f -n __fish_use_subcommand -a runner    -d 'Run Ruby code in the app context'
complete -c rails -f -n __fish_use_subcommand -a new       -d 'Create a new Rails app'
complete -c rails -f -n __fish_use_subcommand -a plugin    -d 'Manage Rails plugins'
complete -c rails -f -n __fish_use_subcommand -a version   -d 'Show the Rails version'
complete -c rails -f -n __fish_use_subcommand -a help      -d 'Show help'
